name: Thomas Kjeldsen
favicon: null
layout_spectrum: 0.008129694731906056
typography_spectrum: 0.13861
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#210408'
    - '#5a4154'
    - '#595e96'
    - '#98bed1'
    - '#7793c2'
  brandStrength: 0.5467765652574599
  lightness: 0.2326768843922764
  saturation: 0.11868535168468952
  rhythmicContrast: 0.9160009559709579
purpose: []
