name: Thomas Kjeldsen
favicon: null
layout_spectrum: 0.16702698334120214
typography_spectrum: 0.13861
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040308'
    - '#121f3d'
    - '#2c4273'
    - '#4472b3'
    - '#6c8abc'
  brandStrength: 0.9273593856487423
  lightness: 0.34777827467769384
  saturation: 0.42313652858138084
  rhythmicContrast: 0.061439419630914927
purpose: []
