typography_spectrum: 0.6462704357609043
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.5806871440696834
  lightness: 0.3894286528494357
  saturation: 0.8280668178437701
  rhythmicContrast: 0.031455509396601876
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8097607101249223
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Thomas Kjeldsen
  email: thomas.kjeldsen@icloud.com
name: Thomas Kjeldsen
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Mobildiskotek Larger Than Life '
    url: 'http://largerthanlife.dk'
    type: external
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Thomas Kjeldsen
content: []
description: A Grid Site
purpose:
  - type: contact
    url: 'mailto:thomas.kjeldsen@icloud.com'
    label: Send mig en e-mail
  - type: external
    url: 'http://facebook.com/thomas.kjeldsen1998'
    label: Min Facebook
