layout_spectrum: 1
favicon: null
name: Thomas Kjeldsen
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.5
  saturation: 0.4231365285813808
  brandColors:
    - '#040308'
    - '#121f3d'
    - '#2c4273'
    - '#4472b3'
    - '#6c8abc'
  lightness: 0.3477782746776938
  rhythmicContrast: 0.06143941963091493
typography_spectrum: 0.13861
